services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/www:/var/www:ro
    depends_on:
      - core
      - workflow
      - vue-portal
      - portal
      - workflow-portal
    ports:
      - "80:80"

  core:
    build: ../finmars-core
    volumes:
      - ../finmars-core/poms:/var/app/poms
    env_file:
      - .env
    environment:
      - DB_NAME=core_realm00000
    depends_on:
      - rabbitmq
      - redis
    ports:
      - "8000:8080"

  # core-worker:

  # core-scheduler:

  core-migration:
    build: ../finmars-core
    env_file:
      - .env
    environment:
      - DB_NAME=core_realm00000
      - INSTANCE_TYPE=job
    depends_on:
      - db    

  workflow:
    build: ../finmars-workflow
    volumes:
      - ../finmars-workflow/workflow:/var/app/workflow
    env_file:
      - .env
    environment:
      - DB_NAME=workflow_realm00000
    depends_on:
      - rabbitmq
      - redis
    ports:
      - "8001:8080"

  # workflow-worker:

  # workflow-scheduler:

  workflow-migration:
    build: ../finmars-workflow
    env_file:
      - .env
    environment:
      - DB_NAME=workflow_realm00000
      - INSTANCE_TYPE=job

  # olap:
  #   build: ../finmars-olap
  #   volumes:
  #     - ../finmars-olap/olap:/var/app/olap
  #   env_file:
  #     - .env
  #   environment:
  #     - DB_NAME=olap_realm00000
  #     - DB_USER=postgres
  #     - DB_PASSWORD=postgres
  #   depends_on:
  #     - db
  #     - rabbitmq
  #     - redis
  #   ports:
  #     - "8002:8080"
  
  authorizer:
    build: ../authorizer
    volumes:
      - ../authorizer/authorizer:/var/app/authorizer
    env_file:
      - .env
    environment:
      - DB_NAME=authorizer
      - DB_PORT=5437
    depends_on:
      - db_authorizer
      - rabbitmq
      - redis
    ports:
      - "8003:8080"

  portal:
    build: ../finmars-portal
    env_file:
      - .env
    ports:
      - "8080:8080" 

  vue-portal:
    build: ../finmars-vue-portal
    environment:
      - NUXT_APP_BUILD_ASSETS_DIR=/realm00000/v/_nuxt/
    env_file:
      - .env
    ports:
      - "8081:8080"

  workflow-portal:
    build: ../finmars-workflow-portal
    environment:
      - NUXT_APP_BUILD_ASSETS_DIR=/realm00000/w/_nuxt/
    env_file:
      - .env
    ports:
      - "8082:8080"

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRESQL_MAX_OPEN_CONNS: 500
    stdin_open: true
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  db_authorizer:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authorizer
      POSTGRESQL_MAX_OPEN_CONNS: 500
    stdin_open: true
    tty: true
    ports:
      - "5437:5432"
    volumes:
      - ./authorizer_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    stdin_open: true
    tty: true

  redis:
    image: redis
    ports:
      - "6379:6379"
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  authorizer_postgres_data:
